config/routes.rb
Artfight::Application.routes.draw do
  resources :participants do
    member do
      post "comment"
    end
  end

  devise_for :users, :controllers => { :sessions => "users/sessions", :registrations => "users/registrations" }

  resources :users

  resources :competitions

  match 'profile' => 'users#show'

  match 'competitions/:id/participate' => 'competitions#participate', :as => :participate
  match 'participants/:id/like' => 'participants#like', :as => :like

  root :to => 'welcome#index'

end

app/models/competition.rb
class Competition
	include Mongoid::Document
	include Mongoid::Paperclip
	include Mongoid::MultiParameterAttributes 
	
	field :begin, type: DateTime
   field :end, type: DateTime
   field :title, type: String
   field :description, type: String
  # field :picture, type: String
   field :status, type: Integer
	STATUS_NAMES = {
		0 => 'Not started',
		1 => 'Running',
		2 => 'Suspended',
		3 => 'Finished'
	}

	has_many :participants

	has_mongoid_attached_file :picture,
									  :styles => { :medium => "300x300>", :thumb => "100x100>" },
									  :url  => "/assets/competitions/:id/:style/:basename.:extension"
									  
	def status_name
		STATUS_NAMES[status]
	end
	
	def is_participating(user)
		if user.nil?
			return false
		end
		self.participants.include? Participant.first(conditions: { user_id: user._id } )
	end
	
	def participating?(user)
		if !user.respond_to? :id
			user = User.find(user)
		end
	    participants.where(:user_id => user.id).all.length > 0
	end	
	
	def running?
		now = Time.now
		self.begin <= now and now <= self.end
	end
	
	def participants_desc
		self.participants.desc(:like)
	end
end

app/controllers/competitions_controller.rb
class CompetitionsController < ApplicationController
  load_and_authorize_resource :except=>[:participate]
  #skip_authorize_resource :only => :participate

  def participate
    @participant = Participant.new
    @competition = Competition.find(params[:id])
    
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @competition }
    end
  end

  # GET /competitions
  # GET /competitions.json
  def index
    #@competitions = Competition.all
    @current_page = 'competitions'

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @competitions }
    end
  end

  # GET /competitions/1
  # GET /competitions/1.json
  def show
    #@competition = Competition.find(params[:id])

    now = Time.now

    if @competition.begin <= now and now <= @competition.end
      @competition.status = 1 if @competition.status == 0
    elsif @competition.end < now
      @competition.status = 3 if @competition.status == 1
    end    
    
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @competition }
    end
  end

  # GET /competitions/new
  # GET /competitions/new.json
  def new
    #@competition = Competition.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @competition }
    end
  end

  # GET /competitions/1/edit
  def edit
    #@competition = Competition.find(params[:id])
  end

  # POST /competitions
  # POST /competitions.json
  def create
    #@competition = Competition.new(params[:competition])
    respond_to do |format|
      if @competition.save
        format.html { redirect_to @competition, notice: 'Competition was successfully created.' }
        format.json { render json: @competition, status: :created, location: @competition }
      else
        format.html { render action: "new" }
        format.json { render json: @competition.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /competitions/1
  # PUT /competitions/1.json
  def update
    #@competition = Competition.find(params[:id])

    respond_to do |format|
      if @competition.update_attributes(params[:competition])
        format.html { redirect_to @competition, notice: 'Competition was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @competition.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /competitions/1
  # DELETE /competitions/1.json
  def destroy
    #@competition = Competition.find(params[:id])
    @competition.destroy

    respond_to do |format|
      format.html { redirect_to competitions_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/competitions_helper.rb
module CompetitionsHelper
end

app/views/competitions/_form.html.erb
<%= form_for(@competition,:html => { :multipart => true }) do |f| %>
  <% if @competition.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@competition.errors.count, "error") %> prohibited this competition from being saved:</h2>

      <ul>
      <% @competition.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :begin %><br />
    <%= f.datetime_select :begin %>
  </div>
  <div class="field">
    <%= f.label :end %><br />
    <%= f.datetime_select :end %>
  </div>
  <div class="field">
    <%= f.label :status %><br />
    <%= f.collection_select :status, Competition::STATUS_NAMES.to_a.sort, :first, :last %>
  </div>

  <div class="field">
    <%= f.file_field :picture %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/competitions/edit.html.erb
<h1>Editing competition</h1>

<%= render 'form' %>

<%= link_to 'Show', @competition %> |
<%= link_to 'Back', competitions_path %>

app/views/competitions/index.html.erb
<h1>Competitions</h1>
<br/>

<p><%= link_to 'Create Competition', new_competition_path if can? :create, Competition %></p>

<% @competitions.each do |competition| %>
<div class="competition">
    <div class="info">
        <%= image_tag competition.picture.url(:thumb), :align=>'left', :style=>'margin-right:20px;' %>
        <h2><%= link_to competition.title, competition %></h2>
        <p><%= competition.description %></p>
    </div>
    <div class="date">
        <i>From <b><%= format_time competition.begin %></b> to <b><%= format_time competition.end %></b></i>
    </div>
    <div style="clear:both"></div>
</div>
    <%#= link_to 'Edit', edit_competition_path(competition) %>
    <%#= link_to 'Destroy', competition, confirm: 'Are you sure?', method: :delete %>
<% end %>

<%#= link_to 'New Competition', new_competition_path %>

app/views/competitions/new.html.erb
<h1>New competition</h1>

<%= render 'form' %>

<%= link_to 'Back', competitions_path %>

app/views/competitions/participate.html.erb
<%= form_for(@participant) do |f| %>
  <% if @participant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@participant.errors.count, "error") %> prohibited this participant from being saved:</h2>

      <ul>
      <% @participant.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.hidden_field :competition_id, :value=>@competition._id %>

  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  
  <div class="field">
    <%= f.label :picture %><br />
    <%= f.file_field :picture %>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/competitions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <%= link_to 'Participate', "/competitions/#{@competition.id}/participate" unless !current_user || @competition.is_participating(current_user) %>
</p>

<p>
  <b>Title:</b>
  <%= @competition.title %>
</p>

<p>
  <b>Description:</b>
  <%= @competition.description %>
</p>

<p>
  <b>Begin:</b>
  <%= format_time @competition.begin %>
</p>

<p>
  <b>End:</b>
  <%= format_time @competition.end %>
</p>

<p>
  <b>Status:</b>
  <%= @competition.status_name %>
</p>

<div class="participants">
  <% max = @competition.participants.size; @competition.participants_desc.each_with_index do |p, index| %>
    <div class="participant">
      <b style="font-size:<%= 17+max*2-index*2 %>px"><%= index+1 %>.</b>&nbsp;
      <i><%= p.user.fullname %></i>
      <div style="text-align:center;">
        <a href="/participants/<%= p.id %>"><%= image_tag p.picture.url(:thumb) %></a>
      </div>
      likes: <%= p.like %>
    </div>
  <% end %>
  <div style="clear:both"></div>
</div>

<% if false %>
  <table>
    <tr>
      <th>User</th>
      <th>Description</th>
      <th>Like</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  
  <% @competition.participants.each do |participant| %>
    <tr>
      <td><%= participant.user.fullname %></td>
      <td><%= participant.description %></td>
      <td><%= participant.like %></td>
      <td><%= link_to 'Show', participant %></td>
      <td><%= link_to 'Edit', edit_participant_path(participant) %></td>
      <td><%= link_to 'Destroy', participant, confirm: 'Are you sure?', method: :delete %></td>
    </tr>
  <% end %>
  </table>
<% end %>

<% if current_user and current_user.admin? %>
  <%= link_to 'Edit', edit_competition_path(@competition) %> |
  <%= link_to 'Back', competitions_path %>
<% end %>