config/routes.rb
Artfight::Application.routes.draw do
  resources :participants do
    member do
      post "comment"
    end
  end

  devise_for :users, :controllers => { :sessions => "users/sessions", :registrations => "users/registrations" }

  resources :users

  resources :competitions

  match 'profile' => 'users#show'

  match 'competitions/:id/participate' => 'competitions#participate', :as => :participate
  match 'participants/:id/like' => 'participants#like', :as => :like

  root :to => 'welcome#index'

end

app/models/participant.rb
class Participant
	include Mongoid::Document
	include Mongoid::Paperclip

	field :description, type: String
	field :like, type: Integer
	
	has_mongoid_attached_file :picture,
									  :styles => { :medium => "300x300>", :thumb => "75x75>" },
									  :url  => "/assets/participants/:id/:style/:basename.:extension"

	belongs_to :competition
	belongs_to :user
	
	has_many :comments, :as => :commentable

end

app/controllers/participants_controller.rb
class ParticipantsController < ApplicationController
  #skip_authorize_resource :only => :create
  load_and_authorize_resource  :except => :like
  
  
  def like
    @participant = Participant.find(params[:id])

    redirect_to :back and return if !@participant.competition.running?

    token = "123123321"
    token = current_user._id.to_s if current_user

    key = 'liked_'+@participant.id.to_s+'_'+token
    
    if !cookies[key]
      @participant.like += 1
      @participant.save!
    end

    cookies[key] = { :value => true, :expires => Time.now + 60*60*24*365}

    redirect_to :back
  end
  
  def already_voted?(participant)
    token = "123123321"
    token = current_user._id.to_s if current_user
    cookies["liked_"+participant._id.to_s+"_"+token]
  end  
  
  def comment
    c = Comment.create(:text=>params[:text], :commentable=>@participant, :user=>current_user)
    redirect_to :back
  end  
  
  # GET /participants
  # GET /participants.json
  def index
    #@participants = Participant.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @participants }
    end
  end

  # GET /participants/1
  # GET /participants/1.json
  def show
    @competition = @participant.competition
    @already_voted = already_voted? @participant
    
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @participant }
    end
  end

  # GET /participants/new
  # GET /participants/new.json
  def new
    #@participant = Participant.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @participant }
    end
  end

  # GET /participants/1/edit
  def edit
    #@participant = Participant.find(params[:id])
    @competition = @participant.competition
  end

  # POST /participants
  # POST /participants.json
  def create
    @competition = Competition.find(params[:participant][:competition_id])
    
    # cannot register more than once to one competition
    if @competition.participating? current_user
      return
    end

    @participant = Participant.new(params[:participant])
    @participant.user_id = current_user._id
    @participant.like = 0

        # TODO: check @participant.competition_id

    respond_to do |format|
      if @participant.save
        format.html { redirect_to @participant, notice: 'Participant was successfully created.' }
        format.json { render json: @participant, status: :created, location: @participant }
      else
        format.html { render action: "new" }
        format.json { render json: @participant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /participants/1
  # PUT /participants/1.json
  def update
    #@participant = Participant.find(params[:id])

    respond_to do |format|
      if @participant.update_attributes(params[:participant])
        format.html { redirect_to @participant, notice: 'Participant was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @participant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /participants/1
  # DELETE /participants/1.json
  def destroy
    #@participant = Participant.find(params[:id])
    competition = @participant.competition
    @participant.destroy

    respond_to do |format|
      format.html { redirect_to competition }
      format.json { head :no_content }
    end
  end
end

app/helpers/participants_helper.rb
module ParticipantsHelper
end

app/views/participants/_form.html.erb
<%= form_for(@participant) do |f| %>
  <% if @participant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@participant.errors.count, "error") %> prohibited this participant from being saved:</h2>

      <ul>
      <% @participant.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.text_field :user_id, :readonly => true %>
  </div>
  <div class="field">
    <%= f.label :competition_id %><br />
    <%= f.text_field :competition_id, :readonly => true %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :picture %><br />
    <%= f.file_field :picture %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/participants/edit.html.erb
<h1>Editing participant</h1>

<%= render 'form' %>

<%= link_to 'Show', @participant %> |
<%= link_to 'Back', competition_path(@competition._id) %>

app/views/participants/index.html.erb
<h1>Listing participants</h1>

<table>
  <tr>
    <th>User</th>
    <th>Competition</th>
    <th>Description</th>
    <th>Like</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @participants.each do |participant| %>
  <tr>
    <td><%= participant.user_id %></td>
    <td><%= participant.competition_id %></td>
    <td><%= participant.description %></td>
    <td><%= participant.like %></td>
    <td><%= link_to 'Show', participant %></td>
    <td><%= link_to 'Edit', edit_participant_path(participant) %></td>
    <td><%= link_to 'Destroy', participant, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Participant', new_participant_path %>

app/views/participants/new.html.erb
<h1>New participant</h1>

<%= render 'form' %>

<%= link_to 'Back', participants_path %>

app/views/participants/show.html.erb
<p id="notice"><%= notice %></p>

<div id="picture" class="grid-5">
<% if @competition.running? %>
	<%= link_to "I like it", like_path(:id=>@participant.id), {:id => "fav", :class => ( @already_voted ? "liked" : "") } %>
<% end %>
<a href="<%= @participant.picture.url %>"><%= image_tag @participant.picture.url(:medium) %></a>


	<blockquote>
		<p><%= @participant.description %></p>
		<p class="author"><cite>&mdash; <%= link_to @participant.user.fullname, @participant %></a></cite></p>
	</blockquote>
	
</div>
<div class="grid-7">
	&nbsp;&nbsp; Rating:<b><%= @participant.like %></b><br/><br/>
	<div id="comments">
		<%= form_tag comment_participant_path(@participant), :method=>"post", :id=>'write-comment' do %>
			<fieldset>
				<legend>Написать комментарий</legend>
				<%= text_area_tag "text", nil, :size=>'30x3', :class=>"form-grid-7" %>
				<%= button_tag "Написать", :class=>"button-special", :type=>"submit" %>
			</fieldset>
		<% end %>
		
		<% def write_comment(comments) %>
			<ol class="listreset comments">
				<% comments.each do |comment| %>
					<li>
						<ul class="listreset meta">
							<li><%= image_tag comment.user.picture.url('thumb') %></li>
							<li><a><% comment.user.fullname %></a></li>
							<li>posted on <%= format_time comment.created_at %></li>
						</ul>
						<div class="body">
							<p><%= comment.text %></p>
							<!--<p class="answer-control"><a>Ответить</a></p>-->
						</div>
						<% #write_comments comment.comments if comment.comments.size > 0
						%>
					</li>
				<% end %>
			</ol>
		<% end %>
		<% write_comment @participant.comments %>
	</div>
</div>

<%#= link_to 'Edit', edit_participant_path(@participant) %> 
<%#= link_to 'Back', participants_path %>