config/routes.rb
Artfight::Application.routes.draw do
  resources :participants do
    member do
      post "comment"
    end
  end

  devise_for :users, :controllers => { :sessions => "users/sessions", :registrations => "users/registrations" }

  resources :users

  resources :competitions

  match 'profile' => 'users#show'

  match 'competitions/:id/participate' => 'competitions#participate', :as => :participate
  match 'participants/:id/like' => 'participants#like', :as => :like

  root :to => 'welcome#index'

end

app/models/user.rb
class User
  include Mongoid::Document
  include Mongoid::Paperclip
  field :remember_me, type: Boolean
  field :first_name, type: String
  field :last_name, type: String
  field :aboutme, type: String
  field :created_at, type: DateTime
  field :updated_at, type: DateTime
  #field :picture, type: String

  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  ## Database authenticatable
  field :email,              :type => String, :null => false, :default => ""
  field :encrypted_password, :type => String, :null => false, :default => ""

  ## Recoverable
  field :reset_password_token,   :type => String
  field :reset_password_sent_at, :type => Time

  ## Rememberable
  field :remember_created_at, :type => Time

  ## Trackable
  field :sign_in_count,      :type => Integer, :default => 0
  field :current_sign_in_at, :type => Time
  field :last_sign_in_at,    :type => Time
  field :current_sign_in_ip, :type => String
  field :last_sign_in_ip,    :type => String

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :first_name, :last_name, :aboutme, :picture, :created_at, :updated_at

  has_mongoid_attached_file :picture,
                            :styles => { :medium => ["300x300>", :jpg], :thumb => ["75x75>", :jpg] },
                            :url  => "/assets/avatars/:id/:style/:basename.:extension"
                            
  belongs_to :role
  has_many :participants, dependent: :delete
  has_many :comments

  validates :email, :uniqueness => { :case_sensitive => false }

  def role?(role)
    if self.role.nil?
      return false
    end
    if role.class == Role
      return self.role == role
    end
    if role.class == String || role.class == Symbol
      return self.role == Role.first(conditions: { name: role.to_s })
    end
    
  end

  def fullname
    s = first_name.to_s + ' ' + last_name.to_s
    s = email if s.length < 2
    s
  end
  
  def admin?
    role?('admin')
  end
  
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
	before_filter :current_item

	def current_item
		@users_cp_class = 'current'
	end

  #before_filter :check_permissions, :only => [:new, :create, :cancel]
  #skip_before_filter :require_no_authentication
 
  def check_permissions
    #authorize! :create, resource
  end

protected

  def after_sign_up_path_for(resource)
  	"/users/#{current_user.id.to_s}/edit"
  end

end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
	before_filter :current_item

	def current_item
		@users_cp_class = 'current'
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  load_and_authorize_resource
  #before_filter :authenticate_user!, :except => [:index]
  before_filter :current_page

  # Does @user = User.find(params[:id])
  #before_filter :load_user, :only => [:show, :edit, :create, :destroy]

  def current_page
    @users_cp_class = 'current'
  end

  # GET /users
  # GET /users.json
  def index
    @users = User.all
    authorize! :list, @users

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user ||= current_user
    
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    # authorize!
    
    # update roles, if can
   
    if can? :assign_roles, current_user
      checked_roles = params[:roles] || {}
      @user.role_id = []
      checked_roles.keys.each do |key|
        Role.first(conditions: {name: key }).users << @user
      end
    end

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    authorize! :destroy, @user
    
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  private
  # GET /users/new
  # GET /users/new.json
  def new
    #@user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  protected
    def load_user
      @user = User.find(params[:id])
    end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email, :readonly=>'true' %>
  </div>

  <div class="field">
    <%= f.label :first_name %><br />
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br />
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :picture %><br />
    <%= f.file_field :picture %>
  </div>
  <div class="field">
    <%= f.label :aboutme %><br />
    <%= f.text_area :aboutme %>
  </div>
  <ul class="field">
    <% Role.all.each do |role| %>
      <li><%= check_box_tag "roles[#{role.name}]", 1, @user.role?(role)  %> : <%= role.name %></li>
    <% end %>
  </ul>
  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
	<tr>
		<th>email</th>
		<th>First name</th>
		<th>Last name</th>
		<th>Picture</th>
		<th>Aboutme</th>
		<th></th>
		<th></th>
		<th></th>
	</tr>

<% @users.each do |user| %>
	<tr>
		<td><%= user.email %></td>
		<td><%= user.first_name %></td>
		<td><%= user.last_name %></td>
		<td><%= image_tag(user.picture.url(:thumb)) %></td>
		<td><%= user.aboutme %></td>
		<td><%= link_to 'Show', user %></td>
		<td><%= link_to 'Edit', edit_user_path(user) %></td>
		<td><%= link_to 'Destroy', user, confirm: 'Are you sure?', method: :delete %></td>
	</tr>
<% end %>
</table>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>E-mail:</b>
  <%= @user.email %>
</p>

<p>
  <b>First name:</b>
  <%= @user.first_name %>
</p>

<p>
  <b>Last name:</b>
  <%= @user.last_name %>
</p>

<p>
  <b>Picture:</b>
  <%= image_tag @user.picture.url('thumb') %>
</p>

<p>
  <b>Aboutme:</b>
  <%= @user.aboutme %>
</p>
  
  <ul class="field">
    <% Role.all.each do |role|
      checked = false
      if !@user.role.nil?
        checked = true if @user.role?(role)
      end
    %>
      <li><%= check_box_tag "roles[#{role.name}]", 1, @user.role?(role), :disabled=>'true'  %> : <%= role.name %></li>
    <% end %>
  </ul>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>