config/routes.rb
Artfight::Application.routes.draw do
  resources :participants do
    member do
      post "comment"
    end
  end

  devise_for :users, :controllers => { :sessions => "users/sessions", :registrations => "users/registrations" }

  resources :users

  resources :competitions

  match 'profile' => 'users#show'

  match 'competitions/:id/participate' => 'competitions#participate', :as => :participate
  match 'participants/:id/like' => 'participants#like', :as => :like

  root :to => 'welcome#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Artfight</title>
	<%= stylesheet_link_tag		"application", :media => "all" %>
	<%= javascript_include_tag "application" %>
	<%= csrf_meta_tags %>
</head>
<body>
	<div id="header">
		<div class="container">
			<div class="grid-1 logo">
				<a>
					<%= link_to image_tag("logo.png", :alt=>'Art fight', :title=>'Art Fight'), root_path %>
				</a>
			</div>
			<div class="grid-11" id="nav">
				<ul class="listreset" style="float:left">
					<li class="<%= @current_page=='competitions' ? 'current' : '' %>">
						<%= link_to 'Competitions', competitions_path %>
					</li>
					<% if @competition and @competition.id %>
						<li class="current"><%= link_to @competition.title, competition_path(@competition.id) %></a></li>
					<% end %>
				</ul>
				<ul class="listreset" style="float:right">
					<!--<li class="current">
						<a>Some really very long fight name</a>
					</li>
					<li><a>Рисуем пейзажи</a></li>
					<li><a>Вызывается Такой-то на дуэль</a></li> -->
					<% if user_signed_in? %>
						<li class="<%= @users_cp_class %>"><%= link_to current_user.fullname, '/profile' %> </li>
						<li><%= link_to('Logout', destroy_user_session_path, :method => :delete) %></li>
					<% else %>
						<li class="<%= @users_cp_class %>"><%= link_to('Login', new_user_session_path)	%></li>
					<% end %>
				</ul>
			</div>
			<div class="clear"></div>
		</div>
	</div>

	<div id="pictures">
		<div class="container">
			<div class="grid-1">
				<button class="arrow nav-left">Назад</button>
			</div>
			<div id="pic-nav" class="grid-10">
				<ul>
					<% if @competition and @competition.participants.size > 0 %>
						<% @competition.participants.each do |p| %>
							<li><a href="<%= participant_path(p) %>"><%= image_tag p.picture.url(:thumb) %></a></li>
						<% end %>
					<% else %>
						<% (1..13).each do |i| %>
							<li><a href="#"><%= image_tag "thumbnails/#{i}.jpg" %></a></li>
						<% end %>
					<% end %>
				</ul>
			</div>
			<div class="grid-1">
				<button class="arrow nav-right">Вперед</button>
			</div>
			<div class="clear"></div>
			<div id="show-other"><a>Изображения (показать) &darr;</a></div>
		</div>
	</div>

	<div id="body" class="container">
		<%= yield %>
		<div class="clear"></div>
	</div>

</body>
</html>